image: 
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet env-certs https
      dotnet restore
      dotnet build
      docker-compose pull
  - name: Run
    command: | 
      dotnet run
      docker-compose up -d

ports:
  - port: 1414
    onOpen: ignore
  - port: 9443
    onOpen: open-browser

vscode:
  extensions:
    - muhammad-sammy.csharp
    - ms-dotnettools.vscode-dotnet-runtime
